# 									
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0

#
# set the target/detector geometry
#/rdecay02/det/setTargetMate G4_SODIUM_IODIDE
# set the target/detector geometry
/rdecay02/det/setTargetLength 58 m
# "Radius" means halfXBox, halfYBox
/rdecay02/det/setTargetRadius 6 m
/rdecay02/det/setDetectorLength 40. m
# Detector"Radius" is set to TargetRadius-InsetRadius
/rdecay02/det/setInsetRadius 3.9 m
# postive puts shield outside cryostat
#/rdecay02/det/setShieldThickness 40 cm
# a negative value puts shield inside cryostat
/rdecay02/det/setShieldThickness 77.6 cm

# next 3 lines need to be: true,false,true or false,true,true
/rdecay02/det/setArapucasInCage true
/rdecay02/det/setDetectorSiPMsOnAcrylic false # this also controls the Acrylic itself, as of 21-June-2023.
/rdecay02/det/setDetectorSiPMsOnCathode true
/rdecay02/det/setDetectorSiPMSize 20.0 cm
/rdecay02/det/setDetectorSiPMThickness 0.1 cm
/rdecay02/det/setDetectorSiPMPhotoCathodeCoverage .20

#
/run/initialize
#
/process/list
#
# rdm is applied only to the target volume

/gps/particle gamma

#/gps/ene/type Gauss
#/gps/ene/mono 1.5 MeV
##/gps/ene/sigma 0.5 MeV
##/gps/ene/min 0.5 MeV
##/gps/ene/max 3.1 MeV

#
# This is for emitting gammas from outside the 3m TargetRadius of Ar
##/gps/energy 0 MeV
##/gps/particle ion
##/gps/ion 81 208 0 0 # Tl208
##/grdm/noVolumes
##/grdm/selectVolume G10



/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 0.1 cm
/gps/pos/halfy 6. m 
/gps/pos/halfz 30. m
/gps/pos/centre -5.98 0 0. m
/gps/pos/confine Target
#/gps/pos/rot1 0 1 0 
##/gps/pos/rot2 0 0 -1

/gps/particle gamma
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/file ../ana/cavgamLAr.txt
#/gps/hist/file ../ana/neutron_distn.txt
/gps/hist/inter Lin

/gps/ang/type iso
#/gps/ang/maxtheta 90 deg

/analysis/setFileName ../data/cavgam_xwall_0
/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
# tracks
/analysis/ntuple/setActivation 3 false
# stepping -- only capatures Arapuca hits if fAPEX=true
/analysis/ntuple/setActivation 4 true
/run/printProgress 1000
/random/setSeeds 1 11
#/control/execute /Users/chur558/rdecay02/macros/vis.mac
# 1.05104 /cm2/sec gammas incident in narrow sliver plane of LAr, just in cryostat, so on x plane of 12*60 m2 this is 7567488.0/sec.
# 75 jobs of 100000 evts is about 1 sec exposure.
/run/beamOn 100000

