# 									
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0


#
/run/initialize
#
/process/list
#
# rdm is applied only to the target volume

/gps/particle gamma

#/gps/ene/type Gauss
#/gps/ene/mono 1.5 MeV
##/gps/ene/sigma 0.5 MeV
##/gps/ene/min 0.5 MeV
##/gps/ene/max 3.1 MeV

#
# This is for emitting gammas from outside the 3m TargetRadius of Ar
##/gps/energy 0 MeV
##/gps/particle ion
##/gps/ion 81 208 0 0 # Tl208
##/grdm/noVolumes
##/grdm/selectVolume G10



/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 0.1 cm
/gps/pos/halfy 6. m 
/gps/pos/halfz 30. m
/gps/pos/centre -7.3 0 0. m
#/gps/pos/confine ColdSkin
#/gps/pos/rot1 0 1 0 
##/gps/pos/rot2 0 0 -1

/gps/particle gamma
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/file ../ana/cavgamLAr.txt
#/gps/hist/file ../ana/neutron_distn.txt
/gps/hist/inter Lin

/gps/ang/type iso
#/gps/ang/maxtheta 90 deg

/analysis/setFileName cavgam_xwall
/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
# tracks
/analysis/ntuple/setActivation 3 false
# stepping -- only captures Arapuca hits if fAPEX=true
/analysis/ntuple/setActivation 4 true
/run/printProgress 1000
/random/setSeeds 1 11
/control/execute /Users/chur558/rdecay02/macros/vis.mac
# 1.05104 /cm2/sec gammas incident in narrow sliver plane of LAr, just in cryostat, so on x plane of 12*60 m2 this is 7567488.0/sec.
# 75 jobs of 100000 evts is about 1 sec exposure.
#/run/beamOn 10000

