# 									
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0

#
# set the target/detector geometry
#/rdecay02/det/setTargetMate G4_SODIUM_IODIDE
# set the target/detector geometry
/rdecay02/det/setTargetLength 58 m
# "Radius" means halfXBox, halfYBox
/rdecay02/det/setTargetRadius 6 m
/rdecay02/det/setDetectorLength 20. m
# Detector"Radius" is set to TargetRadius-InsetRadius
/rdecay02/det/setInsetRadius 3 m
# postive puts shield outside cryostat
#/rdecay02/det/setShieldThickness 40 cm
# a negative value puts shield inside cryostat
/rdecay02/det/setShieldThickness -20 cm


#
/run/initialize
#
/process/list
#
# rdm is applied only to the target volume
/grdm/noVolumes
/grdm/selectVolume Target

/gps/particle gamma

/gps/ene/type Gauss
/gps/ene/mono 1.5 MeV
##/gps/ene/sigma 0.5 MeV
##/gps/ene/min 0.5 MeV
##/gps/ene/max 3.1 MeV


##/gps/pos/type Volume
##/gps/pos/shape Para
##/gps/pos/halfx 0 #2 m
##/gps/pos/halfy 0 #2 m
##/gps/pos/halfz 0 #8 m
##/gps/pos/centre 0. 0. 0. m
#

### from end cap
#/gps/position 0 0 -29 m
#/gps/pos/type Volume
#/gps/pos/shape Para
#/gps/pos/halfx 6 m
#/gps/pos/halfy 6 m
# This is for emitting n's from outside the water shielding
##/gps/pos/centre 0. 6.4 0. m
/gps/pos/centre 0. 5.9 0. m
/gps/pos/type Plane
/gps/pos/shape Rectangle
#/gps/pos/rot1 0 1 0 
/gps/pos/rot2 0 0 -1
/gps/pos/halfx 6 m
/gps/pos/halfy 29 m

/gps/ang/type iso
#/gps/ang/maxtheta 90 deg

#/analysis/setFileName neutron_shield
#/analysis/setFileName neutron_plastic20cm
/analysis/setFileName neutron_vistest
/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
/analysis/ntuple/setActivation 3 true
/analysis/ntuple/setActivation 4 true
/run/printProgress 1000

/control/execute vis.mac

# 0.8 Bq/kg leads to 10 Hz. 10 * piE7 sec is ~31 E7. Let's run 1/10th of one year.
#/run/beamOn 31000000  # 10000
/run/beamOn 3000000
