### Usage: ./sndwrm ../macros/gamma-cavz.mac <floorincm> 
### define aliases for command-line arguments


# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0

/control/alias FLOOR {ARG1}

## New FidVol setting to over-ride default 6,6,30
/sndwrm/det/setHalfFidVol 7. 7. 31 m
/sndwrm/det/setFloorShield {FLOOR} cm

#
/run/initialize
#
/process/list
#
# rdm is applied only to the target volume

/gps/particle gamma


### Cavern
/gps/pos/type Surface
/gps/pos/shape Cylinder
/gps/pos/radius 16. m
/gps/pos/halfz 35. m
/gps/pos/centre 0. -3.0  0. m
/gps/pos/confine OuterAir

#### Floor
##/gps/pos/type Volume
##/gps/pos/shape Para
##/gps/pos/halfx 10.0 m
##/gps/pos/halfy 0.1 m 
##/gps/pos/halfz 35. m
##/gps/pos/centre 0. -13.0  0. m

#/gps/pos/confine ColdSkin
#/gps/pos/rot1 0 1 0 
##/gps/pos/rot2 0 0 -1

/gps/particle gamma
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/file ../ana/cavgamLAr.txt
#/gps/hist/file ../ana/neutron_distn.txt
/gps/hist/inter Lin

/gps/ang/type iso
#/gps/ang/maxtheta 90 deg

#/analysis/setFileName ../ana/cavgam_{FLOOR}cmfl_0walls_None.root
/analysis/setFileName ../ana/cavgamCAV_{FLOOR}cmfl_25cmPbfl_23cmwalls.root
##/analysis/h1/set 0 100 0. 2. MeV
##/analysis/h1/set 1 100 0. 2. MeV
##/analysis/h1/set 6 100 0. 2. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
# tracks
/analysis/ntuple/setActivation 3 false
# stepping -- only captures Arapuca hits if fAPEX=true
/analysis/ntuple/setActivation 4 false
/run/printProgress 100000
/random/setSeeds 1 11
#/control/execute /rcfs/projects/dunelb/more407/FDM3/sndwrm/macros/vis.mac
# 1.05104 /cm2/sec gammas incident in narrow sliver plane of LAr, just in cryostat, so on x plane of 12*60 m2 this is 7567488.0/sec.
# 75 jobs of 100000 evts is about 1 sec exposure.
##/control/execute ../macros/vis.mac
/run/beamOn 40000000
##/run/beamOn 100000000

##/run/beamOn 400001
