#
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0

### WARNING: this line not yet tested, EC, 8-May-2025.
/sndwrm/det/setHalfFidVol 7. 7. 31 m
#

/run/initialize
#
/process/list
###
# annotated_8b.js
/rdecay02/marley/setConfigFile /Users/chur558/marley/examples/config/annotated_8b.js  


# When 'nu_e' is seen in PrimaryGenerator.cc it launches 1 Marley event
/gps/particle nu_e
/gps/position 0 0 0 m
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 5 m
/gps/pos/halfy 5 m
/gps/pos/halfz 28. m
/gps/pos/centre 0. 0. 0. m
#/gps/pos/confine Detector
# This is for emitting e's from the 1.2cm thick coldskin OR the bulk Ar in detector


#/analysis/setFileName  marley_optphys_SN-liv-CEvNS
/analysis/setFileName  ../ana//marley_optphys_b8.root
#/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 320000.
/analysis/h1/set 2 100 0. 320000.
/analysis/h1/set 3 100 0. 320000.
/analysis/h1/set 4 120 0. 24. MeV
/analysis/h1/set 5 120 0. 24. MeV
/analysis/h1/set 6 120 0. 24. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
/analysis/ntuple/setActivation 3 false ## Tracks
/analysis/ntuple/setActivation 4 false ## Steps
/run/printProgress 1000
#/control/execute vis.mac


##/run/beamOn 4 # 10000
/run/beamOn 3600
