# 									
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 2

#
# set the target/detector geometry
#/rdecay02/det/setTargetMate G4_SODIUM_IODIDE
# set the target/detector geometry
/rdecay02/det/setTargetLength 58 m
# "Radius" means halfXBox, halfYBox
/rdecay02/det/setTargetRadius 6 m
/rdecay02/det/setDetectorLength 40. m
# Detector"Radius" is set to TargetRadius-InsetRadius
/rdecay02/det/setInsetRadius 3.9 m
# postive puts shield outside cryostat
#/rdecay02/det/setShieldThickness 40 cm
# a negative value puts shield inside cryostat
/rdecay02/det/setShieldThickness 77.6 cm


#

/run/initialize

#
/process/list
#
# rdm is applied only to the target volume

/gps/particle opticalphoton

#/gps/ene/type Gauss
/gps/ene/mono 3. eV
##/gps/ene/sigma 0.5 MeV
##/gps/ene/min 5 eV
##/gps/ene/max 70 eV

#
# This is for emitting gammas from outside the 3m TargetRadius of Ar
###/gps/energy 0 MeV
###/gps/particle ion
###/gps/ion 19 40 0 0 # K40
###/grdm/noVolumes
###/grdm/selectVolume G10

##/gps/pos/centre 0. 3.0127 0. m

/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 1. m
/gps/pos/halfy 1. m
/gps/pos/halfz 30. m
/gps/pos/centre 0. 3. 0. m
###/gps/pos/confine G10
#/gps/pos/rot1 0 1 0 
##/gps/pos/rot2 0 0 -1

/gps/ang/type iso
#/gps/ang/maxtheta 90 deg

#/analysis/setFileName neutron_shield
#/analysis/setFileName neutron_plastic20cm
#/analysis/setFileName /Volumes/Transcend2TB/G4/data/liquid/k40_G10_wopt
/analysis/setFileName k40_G10_wopt
/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
/analysis/ntuple/setActivation 3 true
/analysis/ntuple/setActivation 4 true
/run/printProgress 1000

/control/execute vis.mac

# 0.8 Bq/kg leads to 10 Hz. 10 * piE7 sec is ~31 E7. Let's run 1/10th of one year.
#/run/beamOn 31000000  # 10000

# scale  Tl208 as 36% of Th232 at 50 mBq/kq
# 0.050 Bq/kg *0.36* 6*60*0.003*1E6*1.65 *1E-3*piE7 is 1.007E9 decays. Let's run 27E6, 0.027 of a year.
# This presumes G10 covers full top of cryostat.

# for Acrylic https://link.springer.com/content/pdf/10.1007/BF02219853.pdf 3 pgm/gm.

## for G10, 4.9 mB/kq
# 4.9 Bq/kg * 6*60*0.003*1E6*1.65 *1E-3*piE7 is 27.4E10 decays. Let's run 27E6, 1E-4^th of a year.

#/run/beamOn 27000000
#/run/beamOn 270000
#/run/beamOn 20

