#
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0

#
# set the target/detector geometry
#/rdecay02/det/setTargetMate G4_SODIUM_IODIDE
# set the target/detector geometry
/rdecay02/det/setTargetLength 58 m
# "Radius" means halfXBox, halfYBox
/rdecay02/det/setTargetRadius 6 m
/rdecay02/det/setDetectorLength 40. m
# Detector"Radius" is set to TargetRadius-InsetRadius
/rdecay02/det/setInsetRadius 3.9 m
# postive puts shield outside cryostat
#/rdecay02/det/setShieldThickness 40 cm

/rdecay02/det/setShieldThickness +77.6 cm


## SiPM SETTINGS ##
/rdecay02/det/setDetectorSiPMsOnAcrylic false ## to look only at APEX-like Arapucas. This shuts off Acrylic AND its SiPMs.
/rdecay02/det/setDetectorSiPMsOnCathode true
/rdecay02/det/setDetectorSiPMSize 20.0 cm
/rdecay02/det/setDetectorSiPMThickness 0.1 cm

/rdecay02/det/setDetectorSiPMPhotoCathodeCoverage .20 #SiPM Coverage
/rdecay02/det/setAcrylicRadius 6. m #Acrylic width/heigth (not larger than 6)
/rdecay02/det/setAcrylicLength 40. m #Acrylic length (not larger than 60)

/rdecay02/material/setG10SpecRef .44 #Anode planes reflectivity
/rdecay02/material/setAcrylicSpecRef .97 #Acrylic walls reflectivity
/rdecay02/material/setLArAbsLength 50 m #Max length photon travel in Argon

#
/run/initialize
#
/process/list
#
# rdm is applied only to the ColdSkin volume
/grdm/noVolumes
/grdm/selectVolume Detector

# When 'geantino' is seen in PrimaryGenerator.cc it launches 1250 uniform, isotropic opticalphotons (100 keV n.r.)
# and it launches them insdie the Acrylic volume, igoring below /gps/pos commands
/gps/particle geantino
/gps/ene/mono 9.686 eV # 128nm
/gps/ang/type iso


# These dimensions for throwing opticalphotons are over-ridden in PrimaryGenerator.cc.
/gps/position 0 0 0 m
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 3.0 m
/gps/pos/halfy 4.5 m
/gps/pos/halfz 20.0 m
/gps/pos/centre 0. 0. 0. m
#/gps/pos/confine Detector




## FILE NAME ## /rcfs/projects/dunelb/chur558/data/pbomb_optphys_MAX10000beam_5sipm_44anode_97acrylic_02
/analysis/setFileName  pbomb_optphys_20sipm_44anode_97acrylic_APEX

## HISTOGRAMS INCLUDED ##
#/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 1300.
/analysis/h1/set 2 100 0. 1300.
/analysis/h1/set 3 100 0. 1300.
/analysis/h1/set 4 100 0. 2. MeV
/analysis/h1/set 5 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV

## Leave below at their hard-coded values, since these aren't working to over-ride! EC, 23-July-2021.
#/analysis/p1/setX 0 10 0. 3. m
#/analysis/p1/setY 0 0. 1300.
#/analysis/p1/setX 1 10 0. 4.5 m
#/analysis/p1/setY 1 0. 1300.
#/analysis/p1/setX 2 20 0. 20. m
#/analysis/p1/setY 2 0. 1300.

#/analysis/p2/setX 0 10 0. 3.0 m
#/analysis/p2/setY 0 10 0. 4.5 m
#/analysis/p2/setX 1 10 0. 3.0 m
#/analysis/p2/setY 1 20 0. 20. m
#/analysis/p2/setX 2 10 0. 4.5 m
#/analysis/p2/setY 2 20 0. 20. m


## T TREES INCLUDED ##
#/analysis/ntuple/setActivation 0 true
#/analysis/ntuple/setActivation 1 true
#/analysis/ntuple/setActivation 2 true
#/analysis/ntuple/setActivation 3 true
#/analysis/ntuple/setActivation 4 true ## Steps
/run/printProgress 1000
##/control/execute ../vis.mac

# SS has neutrons at level of ~1E-11 /cm3/sec from https://books.google.com/books?id=H-DICgAAQBAJ&pg=PA486&lpg=PA486&dq=dark+matter+uranium+and+thorium+contained+in+stainless+steel&source=bl&ots=0CuBLBhG0h&sig=ACfU3U1RCxZ2C11zW-NUBpHb07HerbX6fw&hl=en&ppis=_e&sa=X&ved=2ahUKEwiF45qy2rbnAhU6JzQIHWelCSwQ6AEwAXoECAoQAQ#v=onepage&q=dark%20matter%20uranium%20and%20thorium%20contained%20in%20stainless%20steel&f=false
# And V. Kudryavtsev: https://www.sciencedirect.com/science/article/pii/S0168900208009984 says 1E-11

# For 10cm Acrylic
# So, our cryoskin has 2E-10*0.012*(4*12*60+2*12*12)*1E6 * 3.1415E7 /yr = 238854 evts/yr, so my run here has evtwt=238854/31000000 for a year.

## NUMBER OF EVENTS EACH WITH 1250 PHOTONS ##
##/run/beamOn 4 # 10000
#/run/beamOn 10
/run/beamOn 1000

