#
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0

#
# set the target/detector geometry
#/rdecay02/det/setTargetMate G4_SODIUM_IODIDE
# set the target/detector geometry
/rdecay02/det/setTargetLength 58 m
# "Radius" means halfXBox, halfYBox
/rdecay02/det/setTargetRadius 6 m
/rdecay02/det/setDetectorLength 40. m
# Detector"Radius" is set to TargetRadius-InsetRadius
/rdecay02/det/setInsetRadius 3.9 m
# postive puts shield outside cryostat
#/rdecay02/det/setShieldThickness 40 cm

/rdecay02/det/setShieldThickness +77.6 cm
/rdecay02/det/setAcrylicRadius 3. m
/rdecay02/det/setAcrylicLength 40. m

/rdecay02/det/setDetectorSiPMsOnAcrylic true
/rdecay02/det/setDetectorSiPMsOnCathode true
/rdecay02/det/setDetectorSiPMSize 24.0 cm
/rdecay02/det/setDetectorSiPMThickness 0.1 cm
/rdecay02/det/setDetectorSiPMPhotoCathodeCoverage 0.80

/rdecay02/material/setG10SpecRef 0.44
/rdecay02/material/setAcrylicSpecRef 0.96
/rdecay02/material/setLArAbsLength 50  m

#
/run/initialize
#
/process/list
#
# rdm is applied only to the ColdSkin volume
/grdm/noVolumes
/grdm/selectVolume Detector

# When 'geantino' is seen in PrimaryGenerator.cc it launches 10000 uniform, isotropic opticalphotons
# and it launches them insdie the Acrylic volume, igoring below /gps/pos commands
/gps/particle geantino
/gps/ene/mono 9.686 eV # 128nm
/gps/ang/type iso


# These dimensions for throwing opticalphotons are over-ridden in PrimaryGenerator.cc.
/gps/position 0 0 0 m
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 1 m
/gps/pos/halfy 2.0 m
/gps/pos/halfz 10.1 m
/gps/pos/centre 0. 0. 0. m
#/gps/pos/confine Detector





/analysis/setFileName  /rcfs/projects/dunelb/chur558/data/pbomb_optphys
/analysis/h1/set 1 100 0. 1300.
/analysis/h1/set 2 100 0. 1300.
/analysis/h1/set 3 100 0. 1300.
/analysis/h1/set 4 100 0. 2. MeV
/analysis/h1/set 5 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV

## no se funciona! Neither does it with p1->h1
##/analysis/p1/set 7 100 -3. +3. 0. 1300.

##/analysis/ntuple/setActivation 0 true
##/analysis/ntuple/setActivation 1 true
##/analysis/ntuple/setActivation 2 true
##/analysis/ntuple/setActivation 3 true
##/analysis/ntuple/setActivation 4 true ## Steps
/run/printProgress 1000
#/control/execute vis.mac

# SS has neutrons at level of ~1E-11 /cm3/sec from https://books.google.com/books?id=H-DICgAAQBAJ&pg=PA486&lpg=PA486&dq=dark+matter+uranium+and+thorium+contained+in+stainless+steel&source=bl&ots=0CuBLBhG0h&sig=ACfU3U1RCxZ2C11zW-NUBpHb07HerbX6fw&hl=en&ppis=_e&sa=X&ved=2ahUKEwiF45qy2rbnAhU6JzQIHWelCSwQ6AEwAXoECAoQAQ#v=onepage&q=dark%20matter%20uranium%20and%20thorium%20contained%20in%20stainless%20steel&f=false
# And V. Kudryavtsev: https://www.sciencedirect.com/science/article/pii/S0168900208009984 says 1E-11

# For 10cm Acrylic
# So, our cryoskin has 2E-10*0.012*(4*12*60+2*12*12)*1E6 * 3.1415E7 /yr = 238854 evts/yr, so my run here has evtwt=238854/31000000 for a year.


##/run/beamOn 4 # 10000
/run/beamOn 1000
