# 									
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
#                                                                         
/control/verbose 2
/run/verbose 1
#
# set the target/detector geometry
##/rdecay02/det/setTargetMate G4_Pb
/sndwrm/det/setGDMLfile /rcfs/projects/dunelb/chur558/sndwrm/geom/pathfinder_psyche.gdml
/testem/phys/addPhysics SpacePhysics_QBBC
####/process/em/AddEmRegion InnerRegion G4EmStandardSS ## from xrayTES

#
/run/initialize
#

/process/list
#


# rdm is applied only to the target volume
#/grdm/noVolumes
#/grdm/selectVolume Target

/gps/position 0 0 0 m
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 13 m
/gps/pos/halfy 7 m
/gps/pos/halfz 7 m
/gps/pos/centre 0. 0. 0. m

/gps/particle proton 
#/gps/energy 100 GeV
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/file ../ana/tgraph-spectra_solar/proton_spectra.txt
/gps/hist/inter Lin

/gps/ang/type iso
#
/analysis/ntuple/setActivation 3 true # tracks
/analysis/ntuple/setActivation 4 false # steps

#/analysis/setFileName proton_shielding_cosmic.root
/analysis/setFileName proton_spqbbc_sol.root
#/analysis/setFileName proton_SPQBBC.root
/run/printProgress 1000
/run/beamOn 400000000


 





